[package]
authors = ["wetfloo <yahahaha.1234567890@gmail.com>"]
categories = ["command-line-utilities", "multimedia::audio"]
keywords = ["cli", "music", "audio", "lrc"]
name = "cnova"
description = "A command-line tool to download lyrics for music, quickly"
license = "MIT"
homepage = "https://github.com/wetfloo/cnova"
repository = "https://github.com/wetfloo/cnova"
readme = "README.md"
version = "0.4.0"
edition = "2024"

[profile.release]
lto = "thin"

# Without this, ci builds will fail
[target.'cfg(all(target_os = "linux", any(target_env = "musl", not(any(target_arch = "x86", target_arch = "x86_64")))))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dependencies]
anyhow = "1.0"
# keep-sorted start
clap = { version = "4.6", features = ["derive", "cargo"] }
const_format = { version = "0.2", features = ["fmt"] }
cross-xdg = "2.1"
env_logger = "0.11"
lofty = "0.24"
log = { version = "0.4", features = ["release_max_level_info"] }
num_cpus = "1"
pretty-type-name = "1.0"
rand = "0.10"
reqwest = { version = "0.13", features = [ "json", "query", "socks" ]}
rusqlite = { version = "0.40", features = ["cache"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.28", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
walkdir = "2"
wetutil = "0.3"
# keep-sorted end
