name: release

# Only do the release on x.y.z tags.
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: freebsd-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-freebsd
            command: build
            strip: true

          - os-name: linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: both
            strip: true

          - os-name: linux-x86_64-musl
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
            command: both
            strip: true

          - os-name: linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: both
            strip: true

          - os-name: linux-aarch64-musl
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl
            command: both
            strip: true

          - os-name: windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            command: both
            strip: true

          - os-name: windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            command: build
            strip: true

          - os-name: macos-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            command: both
            strip: true

          - os-name: macos-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            command: both
            strip: true

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: cnova
          target: ${{ matrix.platform.target }}
          changes-file: "CHANGELOG.md"
          release-tag-prefix: "v"
        if: matrix.toolchain != 'beta' && matrix.toolchain != 'nightly'
